service: event-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  graphql:
    handler: src/index.handler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
